# Generated by Django 6.1.1 on 2026-09-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.domain'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='curriculum.lesson'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['domain', 'is_published'], name='idx_course_domain_pub'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty', 'is_published'], name='idx_course_diff_pub'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'sort_order'], name='idx_lesson_course_order'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['lesson', 'chunk_index'], name='idx_chunk_lesson_order'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('lesson', 'chunk_index')},
        ),
    ]
