# Generated by Django 6.1.1 on 2026-09-17 19:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_ai_score', models.FloatField(help_text='AI-assigned score at time of review.')),
                ('override_score', models.FloatField(help_text="Instructor's final score (0–100).", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('override_reason', models.TextField(help_text='Mandatory explanation for the score override.')),
                ('instructor_feedback', models.TextField(blank=True, help_text='Additional feedback for the student.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor Review',
                'verbose_name_plural': 'Instructor Reviews',
                'db_table': 'simulation_instructor_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the scenario presented to the student.')),
                ('role_context', models.TextField(help_text="The role the student assumes (e.g., 'You are a junior attorney...'). Injected as system prompt context.")),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], db_index=True, default='MEDIUM', max_length=10)),
                ('coin_reward', models.PositiveIntegerField(default=50, help_text='Base coins awarded on successful completion (before multiplier).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('max_steps', models.PositiveSmallIntegerField(default=10, help_text='Maximum number of student steps allowed per session.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='Minimum percentage score required to complete successfully.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hint_text', models.TextField(blank=True, help_text='Optional hint text revealed when student requests a hint.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('grading_rubric', models.JSONField(blank=True, default=dict, help_text='JSON grading rubric. Example: {"legal_reasoning": 40, "factual_accuracy": 30, "communication": 30}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulation Case',
                'verbose_name_plural': 'Simulation Cases',
                'db_table': 'simulation_case',
                'ordering': ['course', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], db_index=True, default='PENDING', max_length=15)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0, help_text='Running weighted score (0–100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('steps_taken', models.PositiveSmallIntegerField(default=0)),
                ('error_analysis', models.JSONField(blank=True, default=dict, help_text='Structured error categories and counts. Example: {"logical_errors": 2, "factual_errors": 1}')),
                ('strengths_summary', models.TextField(blank=True)),
                ('weaknesses_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulation Session',
                'verbose_name_plural': 'Simulation Sessions',
                'db_table': 'simulation_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationStepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField(help_text='1-indexed position of this step in the session.')),
                ('student_input', models.TextField(help_text='Raw text submitted by the student for this step.')),
                ('ai_response_raw', models.JSONField(help_text='Full structured JSON response from AI. Schema: { feedback: str, score: float, next_scenario: str, is_final: bool, error_flags: [...], strengths: [...] }')),
                ('step_score', models.FloatField(default=0.0, help_text='Score for this individual step (0–100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('feedback_text', models.TextField(blank=True, help_text='AI feedback text extracted from ai_response_raw.feedback.')),
                ('next_scenario_text', models.TextField(blank=True, help_text='Next scenario/prompt presented to student.')),
                ('is_final_step', models.BooleanField(default=False, help_text='True if this step concluded the session.')),
                ('rag_context_chunks', models.JSONField(blank=True, default=list, help_text='List of document chunk excerpts used as context for this step.')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulation Step Log',
                'verbose_name_plural': 'Simulation Step Logs',
                'db_table': 'simulation_step_log',
                'ordering': ['session', 'step_number'],
            },
        ),
    ]
