# Generated by Django 6.1.1 on 2026-09-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('simulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorreview',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_cases', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Primary lesson whose DocumentChunks are used for RAG grounding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_cases', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='simulationsession',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='simulation.simulationcase'),
        ),
        migrations.AddField(
            model_name='simulationsession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_review', to='simulation.simulationsession'),
        ),
        migrations.AddField(
            model_name='simulationsteplog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='simulation.simulationsession'),
        ),
        migrations.AddIndex(
            model_name='simulationcase',
            index=models.Index(fields=['course', 'is_published'], name='idx_case_course_pub'),
        ),
        migrations.AddIndex(
            model_name='simulationcase',
            index=models.Index(fields=['difficulty', 'is_published'], name='idx_case_diff_pub'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['student', 'status'], name='idx_session_student_status'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['case', 'status'], name='idx_session_case_status'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['student', 'case', '-created_at'], name='idx_session_student_case'),
        ),
        migrations.AddConstraint(
            model_name='simulationsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0), ('total_score__lte', 100)), name='session_score_range'),
        ),
        migrations.AddConstraint(
            model_name='simulationsession',
            constraint=models.CheckConstraint(condition=models.Q(('steps_taken__gte', 0)), name='session_steps_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='instructorreview',
            constraint=models.CheckConstraint(condition=models.Q(('override_score__gte', 0), ('override_score__lte', 100)), name='review_score_range'),
        ),
        migrations.AddIndex(
            model_name='simulationsteplog',
            index=models.Index(fields=['session', 'step_number'], name='idx_step_session_num'),
        ),
        migrations.AddConstraint(
            model_name='simulationsteplog',
            constraint=models.CheckConstraint(condition=models.Q(('step_score__gte', 0), ('step_score__lte', 100)), name='step_score_range'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationsteplog',
            unique_together={('session', 'step_number')},
        ),
    ]
