# Generated by Django 6.1.1 on 2026-09-18 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_question_questionoption_quiz_question_quiz_and_more'),
        ('simulation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Scenario Title')),
                ('accused_name', models.CharField(help_text='Name/identity of the accused or suspect.', max_length=255, verbose_name='Accused Name')),
                ('crime_details', models.TextField(help_text='Detailed factual description of the incident, timeline, and actions.', verbose_name='Crime Details')),
                ('victim_details', models.TextField(blank=True, help_text='Details regarding the victim or affected parties.', verbose_name='Victim Details')),
                ('roles_available', models.JSONField(default=list, help_text="Roles the student can assume (e.g. ['ADVOKAT', 'TERGOVCHI', 'PROKUROR', 'SUDBA']).", verbose_name='Roles Available')),
                ('prompt_template', models.TextField(blank=True, help_text='Custom instructions and legal constraints for AI evaluator.', verbose_name='AI Prompt Template')),
                ('evidence_items', models.JSONField(blank=True, default=list, help_text='List of case evidence, forensic reports, and witness statements.', verbose_name='Evidence Items')),
                ('laws_referenced', models.JSONField(blank=True, default=list, help_text="Applicable legal articles (e.g. ['JK 37-modda', 'JK 104-modda']).", verbose_name='Referenced Laws')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, help_text='Optional link to active simulation case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='simulation.simulationcase')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='curriculum.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, help_text='Textbook lesson whose knowledge base is used by AI for grounding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'Simulation Scenario',
                'verbose_name_plural': 'Simulation Scenarios',
                'db_table': 'simulation_scenario',
                'ordering': ['-created_at'],
            },
        ),
    ]
