# Generated by Django 6.1.1 on 2026-09-17 19:13

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set False to hide from purchase options.')),
                ('price_uzs', models.PositiveBigIntegerField(default=0, help_text='Price in Uzbek Soʻm. 0 = free.')),
                ('price_coins', models.PositiveBigIntegerField(default=0, help_text='Equivalent coin price if paying with coins.')),
                ('welcome_coins', models.PositiveIntegerField(default=0, help_text='One-time coins awarded on activation.')),
                ('coin_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to earned coins (e.g. 1.5 = 50% bonus).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('monthly_simulations', models.PositiveIntegerField(default=5, help_text='Max full simulation cases per month.')),
                ('daily_ai_turns', models.PositiveIntegerField(default=10, help_text='Max AI dialogue turns per day.')),
                ('free_hints', models.PositiveIntegerField(default=3, help_text='Free hints per month before coin deduction.')),
                ('allowed_retries', models.PositiveIntegerField(default=1, help_text='Free retries per simulation case before coin purchase.')),
                ('max_active_sessions', models.PositiveIntegerField(default=1, help_text='Maximum concurrent open simulation sessions.')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription validity in days after activation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'billing_subscription_plan',
                'ordering': ['price_uzs'],
            },
        ),
    ]
