# Generated by Django 6.1.1 on 2026-09-17 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('simulation', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('payment_method', models.CharField(choices=[('REAL_MONEY', "Real Money (So'm)"), ('COINS', 'Coins'), ('PROMO', 'Promotional')], default='PROMO', max_length=20)),
                ('amount_paid_uzs', models.PositiveBigIntegerField(default=0)),
                ('amount_paid_coins', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'billing_user_subscription',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveBigIntegerField(default=0, help_text='Current coin balance. Must never go negative.')),
                ('lifetime_earned', models.PositiveBigIntegerField(default=0, help_text='Total coins ever credited (historical audit).')),
                ('lifetime_spent', models.PositiveBigIntegerField(default=0, help_text='Total coins ever debited (historical audit).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'billing_wallet',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('WELCOME_BONUS', 'Welcome Bonus'), ('TASK_REWARD', 'Task/Simulation Reward'), ('STREAK_BONUS', 'Daily Streak Bonus'), ('REFERRAL_BONUS', 'Referral Bonus'), ('ADMIN_CREDIT', 'Admin Credit'), ('REFUND', 'Refund'), ('SUBSCRIPTION_PURCHASE', 'Subscription Purchase'), ('HINT_PURCHASE', 'Hint Purchase'), ('RETRY_PURCHASE', 'Retry Purchase'), ('ADMIN_DEBIT', 'Admin Debit')], db_index=True, max_length=30)),
                ('amount', models.BigIntegerField(help_text='Positive = credit, negative = debit.')),
                ('balance_after', models.PositiveBigIntegerField(help_text='Wallet balance after this transaction.')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('simulation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='simulation.simulationsession')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='billing.usersubscription')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'billing_wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuotaUsage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quota_usage', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_simulations_used', models.PositiveIntegerField(default=0)),
                ('monthly_hints_used', models.PositiveIntegerField(default=0)),
                ('monthly_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Date when monthly counters were last reset.')),
                ('daily_ai_turns_used', models.PositiveIntegerField(default=0)),
                ('daily_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Date when daily counters were last reset.')),
                ('active_sessions_count', models.PositiveIntegerField(default=0, help_text='Number of currently open simulation sessions.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_usages', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'User Quota Usage',
                'verbose_name_plural': 'User Quota Usages',
                'db_table': 'billing_user_quota_usage',
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_simulations_used__gte', 0)), name='quota_monthly_sims_gte_zero'), models.CheckConstraint(condition=models.Q(('daily_ai_turns_used__gte', 0)), name='quota_daily_turns_gte_zero'), models.CheckConstraint(condition=models.Q(('active_sessions_count__gte', 0)), name='quota_active_sessions_gte_zero')],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'is_active'], name='idx_sub_user_active'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at', 'is_active'], name='idx_sub_expiry'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_subscription_per_user'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='idx_txn_wallet_time'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='idx_txn_type_time'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='wallet_txn_nonzero_amount'),
        ),
    ]
