# Generated by Django 6.1.1 on 2026-09-18 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_question_questionoption_quiz_question_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Curriculum courses assigned to this group.', related_name='groups', to='curriculum.course')),
                ('mentor', models.ForeignKey(help_text='The mentor / instructor managing this cohort.', limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe unique invitation token.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp after which link is no longer valid.')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum number of times this link can be used. 0 = unlimited.')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Total number of times a student joined via this token.')),
                ('is_active', models.BooleanField(default=True, help_text='Allows mentor to deactivate/revoke the invite link manually.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group')),
            ],
            options={
                'verbose_name': 'Group Invitation',
                'verbose_name_plural': 'Group Invitations',
                'db_table': 'groups_group_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'groups_group_membership',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_groups', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_student_group_membership'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['mentor', 'is_active'], name='idx_group_mentor_active'),
        ),
    ]
